### ISSUE TITLE
Add support to multiple collections

### ISSUE THREAD

**Issue by ArthurCamara** [osirrc/terrier-docker#1]
As far as I know, Terrier does not support to index multiple collections at once. The current implementation may not work as expected in such scenarios.

**Comment by lintool** [comment]
Why can't the image index one collection at a time, and place in different locations?

**Comment by ArthurCamara** [comment]
This would work, but i don’t think there is a way to specify in which collection to search. I will dig deeper on other options.

Arthur Barbosa Câmara
Ph.D.Candidate in Computer Science
Delft University of Technology
camara.arthur@gmail.com
A.BarbosaCamara@tudelft.nl
arthur@abcamara.com
+31 0638089057

________________________________

**Comment by lintool** [comment]
The search hook specifies a collection: https://github.com/osirrc2019/jig

```
python run.py search \
    --repo rclancy/anserini-test \
    --collection [name] \
    --topic [topic_file_name] \
    --output /path/to/output \
    --qrels $(pwd)/qrels/qrels.robust2004.txt
```

**Comment by ArthurCamara** [comment]
Yes, but I can’t specify what collection to search in the terrier search command

**Comment by lintool** [comment]
Ask Craig?

**Comment by ArthurCamara** [comment]
will drop him an email

**Comment by ArthurCamara** [comment]
While I'm waiting for an answer from Craig, I think I found an workaround, by creating one copy of Terrier code for each collection. Will give it a shot today.

**Comment by ArthurCamara** [comment]
Should be fixed on https://github.com/osirrc2019/terrier-docker/commit/433de9e270a222d37018da4f44dc57d8ee128dbe

**Comment by cmacdonald** [comment]
Hi,

I never saw this issue before. Easiest way to do this is to make a new etc/ folder for each collection. You can then tell terrier where to look using the TERRIER_ETC env var.

Craig
