### ISSUE TITLE
Problems with run (exception, missing values, duplicate values)

### ISSUE THREAD

**Issue by ryan-clancy** [osirrc/terrier-docker#39]
I've noticed a couple of things when doing the official runs:

I'm seeing these errors in some of the runs:
```
Error in org.terrier.matching.dsms.DFRDependenceScoreModifier java.lang.ClassCastException: org.terrier.structures.postings.bit.BasicIterablePosting cannot be cast to org.terrier.structures.postings.BlockPosting
java.lang.ClassCastException: org.terrier.structures.postings.bit.BasicIterablePosting cannot be cast to org.terrier.structures.postings.BlockPosting
        at org.terrier.matching.dsms.DependenceScoreModifier.scoreFDSD(DependenceScoreModifier.java:441)
        at org.terrier.matching.dsms.DependenceScoreModifier.calculateDependence(DependenceScoreModifier.java:357)
        at org.terrier.matching.dsms.DependenceScoreModifier.doDependency(DependenceScoreModifier.java:310)
        at org.terrier.matching.dsms.DependenceScoreModifier.modifyScores(DependenceScoreModifier.java:191)
        at org.terrier.matching.dsms.DFRDependenceScoreModifier.modifyScores(DFRDependenceScoreModifier.java:87)
        at org.terrier.matching.BaseMatching.finalise(BaseMatching.java:299)
        at org.terrier.matching.daat.Full.match(Full.java:182)
        at org.terrier.querying.LocalManager$ApplyLocalMatching.process(LocalManager.java:459)
        at org.terrier.querying.LocalManager.runSearchRequest(LocalManager.java:845)
        at org.terrier.applications.batchquerying.TRECQuerying.processQuery(TRECQuerying.java:720)
        at org.terrier.applications.batchquerying.TRECQuerying.processQueryAndWrite(TRECQuerying.java:631)
        at org.terrier.applications.batchquerying.TRECQuerying.processQueries(TRECQuerying.java:830)
        at org.terrier.applications.batchquerying.TRECQuerying.processQueries(TRECQuerying.java:743)
        at org.terrier.applications.batchquerying.TRECQuerying$Command.run(TRECQuerying.java:257)
        at org.terrier.applications.AbstractQuerying$AbstractQueryingCommand.run(AbstractQuerying.java:160)
        at org.terrier.applications.CLITool$CLIParsedCLITool.run(CLITool.java:155)
        at org.terrier.applications.CLITool.main(CLITool.java:316)
```

The run files and MAP numbers don't seem to perfectly align with the table in the README. For example, pl2 is missing the "+prox" and "+prox +qe" from the README table. 

There also appears to be some duplicates. For example, "./run.robust04.pl2.txtmap all 0.2241" and "./run.robust04.pl2_prox.txtmap all 0.2241" as well as "./run.robust04.bm25.txtmap all 0.2363" and "./run.robust04.bm25_prox.txtmap all 0.2363" are the same in the run files, but are different in the README table.

`robust04` results:
```
ryan@thinkpad ~/sync/git/jig/azure/output/terrier [azure-script]× $ find . -type f -name "*robust04*" -printf "%p" -exec ~/sync/git/jig/trec_eval/trec_eval -m map ~/sync/git/jig/qrels/qrels.robust04.txt {} \;                                   [16:16:52]
./run.robust04.pl2.txtmap                       all     0.2241
./run.robust04.dph_prox_qe.txtmap                       all     0.2821
./run.robust04.pl2_qe.txtmap                    all     0.2538
./run.robust04.dph_prox.txtmap                          all     0.2479
./run.robust04.dph_qe.txtmap                    all     0.2821
./run.robust04.dph.txtmap                       all     0.2479
./run.robust04.bm25.txtmap                      all     0.2363
./run.robust04.bm25_qe.txtmap                           all     0.2762
./run.robust04.pl2_prox_qe.txtmap                       all     0.2538
./run.robust04.pl2_prox.txtmap                          all     0.2241
./run.robust04.bm25_prox_qe.txtmap                      all     0.2762
./run.robust04.bm25_prox.txtmap                         all     0.2363
```

`core18` results:
```
ryan@thinkpad ~/sync/git/jig/azure/output/terrier [azure-script]× $ find . -type f -name "*core18*" -printf "%p" -exec ~/sync/git/jig/trec_eval/trec_eval -m map ~/sync/git/jig/qrels/qrels.core18.txt {} \;                                     1 [16:16:45]
./run.core18.dph_prox_qe.txtmap                         all     0.3055
./run.core18.bm25.txtmap                        all     0.2326
./run.core18.bm25_prox.txtmap                           all     0.2326
./run.core18.bm25_prox_qe.txtmap                        all     0.2975
./run.core18.bm25_qe.txtmap                     all     0.2975
./run.core18.dph.txtmap                         all     0.2427
./run.core18.dph_prox.txtmap                    all     0.2427
./run.core18.dph_qe.txtmap                      all     0.3055
./run.core18.pl2.txtmap                         all     0.2225
./run.core18.pl2_prox.txtmap                    all     0.2225
./run.core18.pl2_prox_qe.txtmap                         all     0.2787
./run.core18.pl2_qe.txtmap                      all     0.2787
```

Full logs + run files: https://drive.google.com/file/d/1qze83_WPEvOHdsHl2dMbOxfcOcyFZ7xz/view?usp=drivesdk

Lots of info here, so in summary:
- exceptions in the logs
- missing values from readme table (pl +prox and pl +prox + qe)
- duplicate values for [method] and [method]_prox (i.e., bm25 and bm25_prox are both 0.2326 for core18)

Are you guys able to take a look? Could you do a run through with the commands you've provided and ensure all the results align? I can provide the copy of core18 and robust04 we're working with via Slack...

**Comment by cmacdonald** [comment]
Ryan, the scripts we used are in https://github.com/osirrc/terrier-docker/tree/master/bin
In particular, you need a block index in order to do proximity run.

**Comment by ryan-clancy** [comment]
Thanks for pointing me to that!

There's still a disconnect between what's in the table in the README. For example, `config=ql` and `config=ql_qe` are in the [robust04 script](https://github.com/osirrc/terrier-docker/blob/master/bin/robust04.sh) but not in the README. Likewise, `config=pl2_prox` and `config=pl2_prox` are present as examples in the README but are missing entries in the README table with MAP and the robust04 script.

Which conditions should I include in the official run? Can you sync up the robust04 script with the README and I can use that script as the source of truth to build my run script?

Any idea about the exception?

**Comment by cmacdonald** [comment]
IMHO, I think I'm happy with whats in the README, so we can comment out the QL runs. @ArthurCamara let us know your thoughts?

The exception is precisely due to not having a block index. I agree the exception message isn't informative, I'll address that in the next Terrier release.

Craig

**Comment by ArthurCamara** [comment]
I think we are good with BM25, PL2 and DPH + prox, qe.

**Comment by ryan-clancy** [comment]
Alright, this is what I'll run for terrier as it's what I can validate from the README: https://github.com/osirrc/jig/blob/azure-script/azure/osirrc2019/robust04.json#L100

**Comment by ryan-clancy** [comment]
All of the numbers except `./run.core18.pl2_qe.txtmap all 0.2787` look good, maybe a typo in the README?

**Comment by cmacdonald** [comment]
I concur, 0.2787, so have updated README. Can you verify the commit version of the README @r-clancy ?
