### ISSUE TITLE
Inconsistent tags in README

### ISSUE THREAD

**Issue by lintool** [osirrc/terrier-docker#40]
I just noticed in the README, there's `--tag v0.1.5` and `--tag v0.1.6`... I think you might have forgotten to update?

Or you could just say `x.y.z` and write a note something that it refers to the most recent tag... so you don't have to change it every time..

**Comment by ArthurCamara** [comment]
Fixed in https://github.com/osirrc/terrier-docker/commit/496f79475526f08bd03900074c7d1341f2f26851
