### ISSUE TITLE
How do we make this more extensible.

### ISSUE THREAD

**Issue by cmacdonald** [osirrc/terrier-docker#9]
It would be good to have a starting image, that I can extend with more advanced Terrier configurations. What is a good canonical way to do this?

**Comment by ArthurCamara** [comment]
I'm slightly overloaded with a paper submission, so the image is still broken. After it's fixed, you can either fork it or just submit pull requests

**Comment by ArthurCamara** [comment]
I believe this is solved?

**Comment by cmacdonald** [comment]
Ya, I guess so. Its not optimal yet. Lets close for now, in order to stabilise.
